# Generated by Django 5.1.7 on 2025-03-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_order_items_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
